### ISSUE TITLE
Owl v2 loop true and slideBy page breaking loop

### ISSUE THREAD

**Issue by bigegodesign** [gijsroge/OwlCarousel2-Thumbs#15]
Owl v2 (@version 2.0.0) loop set to true and slideBy set to 'page' breaks the loop and rewinds. e.g

loop:true, // Inifnity loop. Duplicate last and first items to get loop illusion.
rewind:false, // Go to first/last.
slideBy:'page'

By the way - excellent work @gijsroge thank you.

**Comment by gijsroge** [comment]
Could you provide a demo showing the issue?

**Comment by sakarya** [comment]
http://tea.bs-internet.com/ same problem..

**Comment by bigegodesign** [comment]
Sorry gijsroge, I completely missed your reply. Unfortunately I do not have a demo or example to show and now i've moved on I can't even recall how to reproduce (apart from above explanation) ... if I get a moment between projects I will endeavour to create a jsfiddle for this and share here.

**Comment by gijsroge** [comment]
Ok, no problem.
