### ISSUE TITLE
can i add slider with thumbs and main both with single nav action. 

### ISSUE THREAD

**Issue by krish-0404** [gijsroge/OwlCarousel2-Thumbs#22]

**Comment by gijsroge** [comment]
No this is not possible with my plugin. I'm not even sure if its possible with owlCarousel 2. You might want to look for a different slider like [flickity](http://flickity.metafizzy.co/options.html#asnavfor) or [swiper ](http://idangero.us/swiper/demos/23-thumbs-gallery.html).

Good luck!
