### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by stormfar** [gijsroge/OwlCarousel2-Thumbs#3]
Hi,

Really like this plugin, so I'm reporting this bug. 
Using Owl Carousel v2.0.0-beta.3, Thumbs v2.0.0

Here is my call:
`
$('.gallery-slider').owlCarousel({
    items: 1,
    thumbs: true,
    thumbImage: true,
    loop: true,
    dots: false
});
`
With `dots: false`, the thumbs do nothing when clicked. Console log returns the error above. With `dots: true`, the thumbs work fine. So I'm temporarily using CSS to hide them. 

Please fix :)

**Comment by gijsroge** [comment]
Thanks for reporting! Published a new release.
