### ISSUE TITLE
OwlCarousel2-Thumbs navigation

### ISSUE THREAD

**Issue by wilco-IO** [gijsroge/OwlCarousel2-Thumbs#30]
Hey there,

First thing awesome coding! i love this slider so much.

Here comes my problem.
I also use the normal owl carousel 2 and there i use the navigation (prev, next).
why can i just not use the normal nav in this thumbs slider?

```
$('.owl-carousel').owlCarousel({
loop: true,
items: 1,
nav:true,
navText : ['<i class="icon ArrowLeft" aria-hidden="true"></i>','<i class="icon ArrowRight" aria-hidden="true"></i>'],
thumbs: true,
thumbsPrerendered: true,
thumbContainerClass: 'owl-thumbs',
thumbItemClass: 'owl-thumb-item'
});
```

Kind regards,

Wilco-IO

**Comment by gijsroge** [comment]
Please provide an example on codepen so I can see the issue.
