### ISSUE TITLE
Thumbs container width + scroll

### ISSUE THREAD

**Issue by WPThemer** [gijsroge/OwlCarousel2-Thumbs#4]
Hi, its really nice improvement and I am gonna use it in one of my theme, however I was wondering is it possible to give X number of visible thumbs for example if I have 20 images, obviously 20 things cannot be shown in one row so I define

visibleThumbs:5

and soon it it scrolls to slide 6 thumbs also scroll to 6-10, currently its difficult to adopt if we have more images..

thanks

**Comment by gijsroge** [comment]
Owl Carousel 1 has this option http://owlgraphic.com/owlcarousel/demos/sync.html

I'm not planning on making this i'm afraid.
