### ISSUE TITLE
Using thumbs as another owl carousel causes issues.

### ISSUE THREAD

**Issue by ImranBug** [gijsroge/OwlCarousel2-Thumbs#6]
When using next and previous arrow of thumbs carousel it triggers the first slide in parent carousel as well. How can I stop that?

Also note that to make the thumbs behave as a separate owl carousel I had to keep the "owl-thumbs" class and "data-slider-id" on a parent div of thumbs carousel.

**Comment by ImranBug** [comment]
Fixed !!

I changed this line:

```
$(this._thumbcontent._thumbcontainer).on('click', this._thumbcontent._thumbcontainer.children(), $.proxy(function (e) {
```

To this line:

```
$('.owl-thumb-item', this._thumbcontent._thumbcontainer).on('click', this._thumbcontent._thumbcontainer.children(), $.proxy(function (e) {
```

The problem was it was taking the click on arrows as a click on thumb image.

**Comment by bogdaniel** [comment]
can you provide an example for you way i'm having the same problem and didn't figure out your comment. it didn't work not even if i changed the line. I added the class and data-slider-id on owl-stage

**Comment by ImranBug** [comment]
If you can create a jsfiddle I will love to point out what is different then my solution but I believe there is a better solution in owl carousel 2 -- check this fiddle - http://jsfiddle.net/esedic/va15m3bL/

**Comment by ImranBug** [comment]
Can you create a fiddle? It would be easier to analyze what is different that you did.
