### ISSUE TITLE
Thumbnail target's wrong slide?

### ISSUE THREAD

**Issue by robmilnes** [gijsroge/OwlCarousel2-Thumbs#9]
As per this example;

http://justvehiclegraphics.co.uk/car-graphics-dev

It seems the thumbnails are targeting the wrong slides when you show more than one item at a time, maybe I could be doing something wrong - but I can't see where in such a simple process to get it going. :/

**Comment by gijsroge** [comment]
It looks like its working fine for me? What do you mean by "show more than one at a time"?

**Comment by cramdesign** [comment]
If you set `items` to anything other than `1`, the thumbnails are not properly clickable. For example:

```
$('.owl-carousel').owlCarousel({
        items: 2
});
```

Only the first and third thumbs are clickable with 5 images total.

**Comment by gijsroge** [comment]
Not in scope of project.
